SET(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_WIN32_WINNT=0x0600 -DWIN32_LEAN_AND_MEAN")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_WIN32_WINNT=0x0600 -DWIN32_LEAN_AND_MEAN")

# which compilers to use for C and C++
find_program(CMAKE_RC_COMPILER NAMES ${CROSS_TRIPLE}-windres)
find_program(CMAKE_C_COMPILER NAMES ${CROSS_TRIPLE}-gcc-posix)
find_program(CMAKE_CXX_COMPILER NAMES ${CROSS_TRIPLE}-g++-posix)

SET(CMAKE_FIND_ROOT_PATH  /usr/${CROSS_TRIPLE})

SET(CMAKE_FIND_LIBRARY_SUFFIXES ".so;.a")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)